### ISSUE TITLE
Adding feature to delete bib record

### ISSUE THREAD

**Issue by lrichelle** [ExLibrisGroup/barcode-fast-withdraw#1]
Hi,
In Alma, when deleting the item, one can choose to delete / suppress / keep the Holding record, but also to delete or suppress the Bib record that has no other holding.
It would be fine if such a feature was available here also ! 
best, 
Laurence 
ULiège Library

**Comment by ori229** [comment]
Hi Laurence,
The Cloud App is based on the API documented here: https://developers.exlibrisgroup.com/alma/apis/docs/bibs/REVMRVRFIC9hbG1hd3MvdjEvYmlicy97bW1zX2lkfS9ob2xkaW5ncy97aG9sZGluZ19pZH0vaXRlbXMve2l0ZW1fcGlkfQ==/
Currently, the API supports only the handling of the Holding record. When the API will be enhanced to support the handling of the Bib record we will add this feature to the Cloud App.
Ori
