### ISSUE TITLE
Enhancement request - Delete bibliographic record if deleting last holdings

### ISSUE THREAD

**Issue by jonahhighmanUWA** [ExLibrisGroup/barcode-fast-withdraw#3]
Hey team, I love this app. It was one of the features I was missing from my previous organisation's LMS, a 'scan to delete' feature.

I use the option to delete the holdings record. It would be very beneficial to have the same delete/suppress/do nothing options for the linked bibliographic record.

For example, if I delete an item, I want to delete the holdings if its the last item, and **also** the bib if it's the last holdings. Otherwise we get leftover bib records with nothing attached to them, and we have to go back and clean them up manually.

Thanks for considering!

**Comment by patriciawf** [comment]
I second this - we actually didn't realise it didn't delete the bibs until recently. Rude awakening with 6000+ bibs now needing deleting ;) The app is great but it would be great if it deleted the bib for last holdings deletions too.

**Comment by ori229** [comment]
Implemented! Please try the new release and let us know if you find any issues.

**Comment by jonahhighmanUWA** [comment]
Hi @ori229, I have tried this out in our sandbox and I now get the new options for Bibs Retain, Suppress and Delete.

However I selected 'Delete' and it did not delete the bib, only suppress it :(

Thanks for your help!

**Comment by ori229** [comment]
Sorry... a small typo caused a bug.  Fixed now
https://github.com/ExLibrisGroup/barcode-fast-withdraw/commit/60639fdcad58da4ac6ad4d8fc8c100a959e230ee

**Comment by jonahhighmanUWA** [comment]
Great! Thank you, appears to be working :)
